apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2am-gateway-manager
  labels:
    name: wso2am-gateway-manager
spec:
  replicas: 1
  selector:
    name: wso2am-gateway-manager
  template:
    metadata:
      labels:
        name: wso2am-gateway-manager
    spec:
      containers:
      -
        name: wso2am-gateway-manager
        image: wso2/am-gateway-manager-1.9.1:1.0.0
        ports:
        -
          containerPort: 8280
          protocol: "TCP"
        -
          containerPort: 8243
          protocol: "TCP"